# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge
  enable_coderay: true

permalink: blog/:year/:month/:day/:title.html
encoding: "utf-8"
future: true
lsi: false
safe: true

blog:
    name: 踏学吾痕
    description: 不求深刻，只求简单。
    title: 踏学吾痕的博客
    url: github.com/LZHD
    duoshuo: LZHD
    tongji: LZHD
author:
    name: LZHD
    email: brucefxq@gmail.com
    weibo: http://weibo.com/FXQLZHD
    github: https://github.com/LZHD
    logo: /res/img/psb.jpg
