title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge
  enable_coderay: true

permalink: blog/:year/:month/:day/:title.html
encoding: "utf-8"
future: true
lsi: false
safe: true

blog:
    name: LZHD
    description: 不求深刻，只求简单。
    title: 我不想一直是小白的博客
    url: github.com/LZHD
    duoshuo: LZHD
    tongji: LZHD
author:
    name: 我不想一直是小白
    email: brucefxq@gmail.com
    weibo: http://weibo.com/FXQLZHD
    github: https://github.com/LZHD
    logo: /res/img/psb.jpg
