markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: true
safe: false



blog:
    name: Daodaoliang Blog                               # 博客名称
    description: I am daodaoliang who are you?           # 博客描述
    title: 徐景亮的博客                                  # 网页标题
    url: daodaoliang.github.io                           # 博客地址
    duoshuo:                                             # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name: 徐景亮                                         # 作者名称
    email: daodaoliang@yeah.net                          # 邮箱地址
    weibo:                                               # 微博地址
    github: https://github.com/daodaoliang               # GitHub地址
    logo: /res/img/psb.jpg                               # logo地址
    douban:
        name: http://www.douban.com/people/103498505/    # 豆瓣地址名称
        key: 07e5af1c9cee1a1a17b10d55d6ca4e4e            # 豆瓣API Key
