markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
highlighter: rouge

permalink: blog/:year/:month/:day/:title.html
paginate: 7
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true
gems: [jekyll-paginate]

blog:
    name: Daodaoliang
    description: 日日当精进 但求无愧 
    title: 刀刀亮的博客
    url: daodaoliang.com
    duoshuo: daodaoliang
    tongji: daodaoliang
    qiniu: # 七牛云地址
author:
    name: 徐景亮
    email: daodaoliang@yeah.net
    weibo: http://weibo.com/u/5336437516
    github: https://github.com/daodaoliang
    logo: /res/img/psb.jpg
    douban:
        name: http://www.douban.com/people/103498505/
        key: 07e5af1c9cee1a1a17b10d55d6ca4e4e        
