markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
highlighter: rouge

permalink: blog/:year/:month/:day/:title.html
paginate: 7
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true
gems: [jekyll-paginate]

blog:
    name: LZHD
    description: 不求深刻，只求简单。
    title: 我不想一直是小白的博客
    url: github.com/LZHD
    duoshuo: LZHD
    tongji: LZHD
    qiniu: # 七牛云地址
author:
    name: 樊兴强
    email: brucefxq@gmail.com
    weibo: http://weibo.com/u/5336437516
    github: https://github.com/LZHD
    logo: /res/img/psb.jpg
    douban:
        name: http://www.douban.com/people/103498505/
        key: 07e5af1c9cee1a1a17b10d55d6ca4e4e        

theme: jekyll-theme-cayman